name: Automerge
on:
    push:
        branches:
        - default

permissions:
    contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: pantheon-systems/upstream-update-automerge@v1
          env:
            PAT_TOKEN: ${{ secrets.AUTOMERGE_SANDBOX_PAT }}